### ISSUE TITLE
presets kubernetesAttributes not available for operator helm chart

### ISSUE THREAD

**Issue by tudrzal** [open-telemetry/opentelemetry-helm-charts#1030]
Hi,
we'd like to use:
```
presets:
  kubernetesAttributes:
    enabled: true
```
however this seems to be helm chart option of Collector helm chart only, not Operator helm chart.
We're using Operator helm chart, which is recommended and manages Collector inside. However I don't see possibility to configure Operator helm chart to use presets.

We're trying to collect, process and export tracing within our kubernetes environment. Could you please advice us which helm chart to use and how to achieve automatic enrichment of tracing telemetry with k8s context?

Thanks

**Comment by TylerHelmuth** [comment]
The current operator chart does not install any `OpenTelemetryCollector` custom resources, which is where a preset like `kubernetesAttributes` would be useful. When using the `opentelemetry-operator` chart, you must install `OpenTelemetryCollector` CRs manually once the operator is successfully installed.

Here are some open issues around the topic of including `OpenTelemetryCollector` CRs as part of the install:
- https://github.com/open-telemetry/opentelemetry-helm-charts/issues/69
- https://github.com/open-telemetry/opentelemetry-helm-charts/issues/677

**Comment by tudrzal** [comment]
I'm not sure which opentelemetry collector CRs should I install.
I'm supposing the purpose of Operator helm chart is to make life easier and avoid installing Collector helm chart. I'm confused now what to do if I require kubernetesAttributes presets (apart standard receivers, pipelines, exporter, tail-sampling processor). I didn't find advice in documentation either. Do I even need Operator helm chart or should I use only Collector and in which cases?
Thank you very much for any advice

**Comment by Allex1** [comment]
@tudrzal I'd say that currently the operator chart requires more work and investment in order to implement an otel pipeline than the collector one which had more contributions but relies on native k8s objects (daemonset, deployment...etc). 
If you're unsure which one to use you should probably choose the collector one.

**Comment by ferrucc-io** [comment]
I installed the Operator thinking it was going to be the happy path of Otel on a K8s cluster, but ended up regretting it because of not being able to use presets and having to manually set things up like Cluster roles.

The docs here are very confusing. I wish there was something recommending to us the Collector upfront with a couple of presets.

**Comment by TylerHelmuth** [comment]
@ferrucc-io Can you be more specific with what docs were confusing?

**Comment by M0NsTeRRR** [comment]
> I installed the Operator thinking it was going to be the happy path of Otel on a K8s cluster, but ended up regretting it because of not being able to use presets and having to manually set things up like Cluster roles.
> 
> The docs here are very confusing. I wish there was something recommending to us the Collector upfront with a couple of presets.

Faced the same issue just now, need to apply a rbac manifest on top of it

**Comment by TylerHelmuth** [comment]
The operator chart cannot include the same preset concept as the collector chart since it does not install OpenTelemetryCollector CRs.

The Operator, and now its chart, do have better support for automatically setting up RBAC: https://github.com/open-telemetry/opentelemetry-helm-charts/issues/1224.

We are adding the new [`opentelemetry-kube-stack` chart](https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-kube-stack) which will have preset support because it will install both the operator and the collector CR.

I am closing this as not planned since the operator will not have presets for the collector, since it does not install it.
