### ISSUE TITLE
ruby otlp exporter can't send traces to the collector

### ISSUE THREAD

**Issue by alicyn** [open-telemetry/opentelemetry-helm-charts#163]
I am using the opentelemetry-ruby exporter (otlp).
https://github.com/open-telemetry/opentelemetry-ruby/tree/main/exporter/otlp

We have enabled auto-instrumentation per the app, but the rails application logs are showing these errors: 
`E, [2022-04-05T22:37:47.838197 #6] ERROR -- : OpenTelemetry error: Unable to export 499 spans`

The otel collector was installed as a daemonset, and I confirmed it is running on all the nodes.

I also set the following env variables within the app:
```
OTEL_LOG_LEVEL=debug
OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://0.0.0.0:4318/v1/traces
OTEL_EXPORTER_OTLP_ENDPOINT=http://0.0.0.0:4318
```

I don't think `http://0.0.0.0:4318` is a valid endpoint, since curling this address from the rails/ruby app returns "Connection Refused". However I am able to curl `http://<OTEL_POD_IP>:4318` which returns `404 page not found`. 
How can get I get an endpoint to the daemonset agent if there's no actual service for the collector? What am I doing wrong here?

The Debug Log level variable doesn't seem to produce any additional information in the logs.

UPDATE:
This has been fixed by enabling the standalone collector in addition to the daemonset agents, which creates a Service that I can use as an endpoint. This isn't made clear in the documentation, that you need both modes enabled in order for this to work. I don't understand the use-case of only enabling the daemonset without a service, which is the default setting in this helm chart.

**Comment by TylerHelmuth** [comment]
@alicyn thanks for reporting your issue and experience.

I think you are right that the current default values.yaml does create a daemonset version of the collector that is tricky to interact with 😬.  Can you try installing only the agent again and send data to `http://<Node-IP>:4318`?  The daemonset should be "stealing" port 4318 on the node and and data sent to `http://<Node-IP>:4318` will be sent to the instance of the collector running on that node.

In #159 we are discussing switching the default mode to be deployment instead of daemonset.
