### ISSUE TITLE
Allow setting lifecycle policies to collector pods

### ISSUE THREAD

**Issue by juissi-t** [open-telemetry/opentelemetry-helm-charts#193]
When scaling down nodes in a Kubernetes cluster, Python services using Opentelemetry libraries tend to hang on shutdown, because the Otel collector pod (daemonset managed) gets terminated before the Python service manages to flush its final traces to the collector. 

To make the error less likely, it would be great, if the collector helm chart would allow using Kubernetes lifecycle hooks, so that I could set a `preStop` commad to wait for some time before terminating the pod.

Looks like the container image is based on `scratch` and has no tools installed, so support for init containers to copy a statically linked `sleep` command to the main container would also be needed to support this use case.

**Comment by TylerHelmuth** [comment]
Hello @juissi-t, thanks for the issue.

I am not opposed to this feature request, but I am curious about a couple things. 

- How long would the collector need to wait before being allowed to shutdown?  
- Is there any way to use preStop commands with the existing image to meet these needs?
- Instead of changing the collector image, could the operator be utilized in some way instead?

**Comment by juissi-t** [comment]
> * How long would the collector need to wait before being allowed to shutdown?

Our API services have a `sleep 5` as their `preStop` hook, so that kube-proxy has enough time to remove them from rotation before SIGTERM signal is sent to them. So in theory, new requests might arrive up to 5 seconds after the worker-to-be-scaled-down sends SIGTERM signals to all pods. After that, the pod still needs to handle any requests in flight. They might take seconds, but a 15 second pause for OTel collector would probably be enough to handle those requests and send the traces in.

> * Is there any way to use preStop commands with the existing image to meet these needs?

Looks like the opentelemetry-collector-contrib image we use is based on the `scratch` image, so it doesn't have any shell tools available. To get `sleep` injected to the main container, we would need to e.g. utilize init containers.

I couldn't find any configuration option for the collector to set a shutdown timeout or something similar.

> * Instead of changing the collector image, could the operator be utilized in some way instead?

I couldn't find anything related to pod lifecycle in the operator CRD, so I think it would not help in this situation.

**Comment by TylerHelmuth** [comment]
I think the lifecycle hook is something we can add to the charts, but for your particular needs, I think adding `sleep` to the image is going to be tricky; I don't expect the maintainers of the collector to want to add anything extra to the image.  You should open an issue in [opentelemetry-collector-releases](https://github.com/open-telemetry/opentelemetry-collector-releases/issues) to see what they think of the idea.

In the meantime, you could also look into the [python instrumentation](https://github.com/open-telemetry/opentelemetry-python) to see if there is something that could be modified so that things don't hang if the instrumentation exporter can't reach its destination. 

Are you planning to submit a PR for this issue that allows setting lifecycle hooks?  If so, I will assign this issue to you.

**Comment by juissi-t** [comment]
Yes, I can create a PR for the changes. Will try to work on it tomorrow.

**Comment by juissi-t** [comment]
Pull request ready for review.
