### ISSUE TITLE
Add example folder with common values.yaml scenarios for operator chart

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-helm-charts#260]
It would be nice to have some example values.yaml for common scenarios customers might have.  Like the collector chart, these examples can be used by customers to see how the values.yaml affects the install and can be used by PR reviewers to validate changes.

Similar to https://github.com/open-telemetry/opentelemetry-helm-charts/issues/138

**Comment by TylerHelmuth** [comment]
@Allex1 are you free to work on this?

**Comment by dmitryax** [comment]
@Allex1 since you did many updates to the operator chart, would you consider becoming a code owner for that chart and possibly an approver in this repo? This will require a bit more involvement tho. Also you need to [request a membership](https://github.com/open-telemetry/community/blob/main/.github/ISSUE_TEMPLATE/membership.md) in OpenTelemetry. Let us know if you are interested

**Comment by Allex1** [comment]
@dmitryax yeah, I'd be interested in that. Who would be the second sponsor?

**Comment by TylerHelmuth** [comment]
@dmitryax and I can sponsor.

**Comment by Allex1** [comment]
Opened https://github.com/open-telemetry/community/issues/1100 . Thanks guys.

**Comment by TylerHelmuth** [comment]
@Allex1 do you have any scenarios you want covered by Examples?

**Comment by Allex1** [comment]
@TylerHelmuth I'm not sure our use cases are something other users would appreciate as we run the operator/collector on clusters which we are not admins on so clusterrole/webhooks need to be disabled and sideloaded by other means.
