### ISSUE TITLE
Set better default resources

### ISSUE THREAD

**Issue by MarkAndersonTrocme** [open-telemetry/opentelemetry-helm-charts#272]
The opentelemetry-collector [only defines limits by default](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/values.yaml#L194-L197),  if you don’t specify requests, Kubernetes will automatically set requests to equal to Pod’s limits. This means that with the default Helm  values, opentelemtry will take up 2Gb and 1cpu, which is insane.

I think there should be default requests set so that K8s does not schedule these pods with such high resources.

**Comment by TylerHelmuth** [comment]
This is an interesting topic since it really comes down to "what should the chart suggest as a starting point for resources". The current value came from the old standaloneCollector value, which was set high to accommodate the "both" mode where agent collectors forwarded traces to a standalone collector. 

The collector is efficient, but in my experience it does take a some resources to run properly. I think we could lower this default value tho since the old "both" mode is no longer supported by a single instance of the chart.
