### ISSUE TITLE
[DEMO] allow specifying external service type

### ISSUE THREAD

**Issue by joshleecreates** [open-telemetry/opentelemetry-helm-charts#431]
Thinking about @puckpuck's comment in SIG last week about external services: It would be great to be able to specify whether or not and how to expose external services from a custom values.yaml. I think adding a values option like `externalServiceType: NodePort|ClusterIP|LoadBalancer` would fit most use cases. 

Jaeger is already handled separately from the other components. What I need to think through before making a PR (or maybe somebody has a suggestion): how to mark the services that should be exposed? Right now I believe that would include the feature flag service UI, loadgenerator and frontend. Did I miss any?

**Comment by puckpuck** [comment]
I was thinking, similar to how we have a `servicePort` property for each component, we also get a `serviceType` property.  This should default to `ClusterIP` and we let the user specify which component gets exposed differently.  In some cases they may just Loadbalaner them all, or mix and match with NodePort because EKS requires a nodeport service for ALB ingress.

I don't think we need to worry about doing ingress routes.  That gets into an area that I feel is best served with docs... but we should still provide the facilities for our services to work with solutions that will overlay ingress routes with the helm chart.
