### ISSUE TITLE
OpenTelemetry demo: we cannot send traces from the frontend through ingress

### ISSUE THREAD

**Issue by jessitron** [open-telemetry/opentelemetry-helm-charts#766]
I'm running the OpenTelemetry demo in Kubernetes. It's in EKS on AWS. I added an ingress (backed by an AWS ALB), so that it is publicly accessible. The ingress routes /v1/traces to the collector, and everything else to the frontend-proxy.

This resulted in 502 errors from the ALB when trying to connect to the collector, while the frontend-proxy endpoints worked fine.
The ALB access logs indicated that it was unable to establish a connection to the collector.

Thanks to @TylerHelmuth, the solution is to add to the collector's OTLP HTTP receiver configuration:
`endpoint: 0.0.0.0:4318`
or 
`endpoint: ${MY_POD_IP}:4381`

0.0.0.0 works for both port forwarding and ingress; ${MY_POD_IP} works for ingress but not port-forwarding.

The [current setting](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/d566388a31a7317c7a13afbeab8c02b63daec785/charts/opentelemetry-demo/values.yaml#L625) of `endpoint: 127.0.0.1:4381` works ONLY for port-forwarding.

Consider going back to 0.0.0.0, to work for both? I spent days troubleshooting this 😢

**Comment by TylerHelmuth** [comment]
@puckpuck we caused this via https://github.com/open-telemetry/opentelemetry-helm-charts/pull/735.  

If putting the demo behind an ingress is a common enough practice (which I assume it is based on the number of vendor forks of the demo), I think we do want to make it easier to handle this situation.  I don't feel comfortable using `0.0.0.0` as a default value, even in the demo, since we'd be breaking our own [Security Best Practices](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#receivers-and-exporters).  Maybe there is a way to clearly document how the default value affects the ingress in the values.yaml and in the README?
