### ISSUE TITLE
Support hostAliases customization in otel collector

### ISSUE THREAD

**Issue by ethernoy** [open-telemetry/opentelemetry-helm-charts#81]
We can add hostAliases customization to otel collector helm chart. 

https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/ 

I am happy to submit a PR for this :)

**Comment by dmitryax** [comment]
@ethernoy sorry for the delayed response? why it must be part of this helm chart? can it be deployed separately?

**Comment by mayoatte** [comment]
I think this would solve a problem we are having at the moment. We need to configure some applications to point to the open telemetry collector (app pods are on the same node as the daemonset pod) in a static way (can't use environment variables). We are having a hard time getting this working because we can't use the downward api.

**Comment by dmitryax** [comment]
Ok, it sounds reasonable. Feel free to submit a PR
