### ISSUE TITLE
Make collector chart have a single responsibility

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-helm-charts#91]
Bringing up a dedicated issue from the comment https://github.com/open-telemetry/opentelemetry-helm-charts/issues/3#issuecomment-938505996 and PR https://github.com/open-telemetry/opentelemetry-helm-charts/pull/86.

The proposal is to remove the option to deploy both agentCollector and standaloneCollector with data automatically forwarded through from agent to standalone collector. This will significantly reduce complexity of the chart and resolve some configuration issues

Action items:
- [x] #157
- [x] #158

**Comment by txomon** [comment]
> 1. Add an upgrade section in README that will include examples on how to migrate from deployment of both modes to the 2 separate releases.

I have done this in https://github.com/open-telemetry/opentelemetry-helm-charts/pull/86/commits/3078c4903a9bdfa1f8ed2dfcec3932d05bd8c239 hopefully it's what you were looking for. In general I believe it's not good to document so much because it's harder to maintain, but I do agree that it's easier to explain this way.

> We also need to make sure the upgrade doesn't replace existing customizations that users may have by the new default configs. We could do some sort of backward compatibility by manipulating deprecated configurations. But it might be too big of an overhead. What I believe we should do is to introduce a pre-upgrade validation step that would identify old configurations in the user's values.yaml that would be dropped and block the upgrade. I believe this can be achieved with values.schema.json

I have been looking into this, but I can't find a good way to forbid a key to exist (the schema doesn't seem to validate anything else but the keys that are documented). Do you have any idea on how it could be done?

> Also I see your PR is doing many changes. Do you see a way to break it down into smaller independent PRs? 

I'm afraid this is the only way I have found. I started thinking splitting it in two parts, but I wasn't able find a clean split that would allow for a logical middle step. The only other way I could come up with was to provide two different charts that would support the old configuration but that would make a very messy outcome for later unifying them.

> It should be good if it'll require more upgrade sections in the README for each configuration change.

Hopefully this last commit I linked satisfies the instructions for upgrading from 0.6.0. Also, in the initial version I had already further documented the previously available enhancements (container logs, host monitoring, memory limiter) in a way that are more straightforward to use now (also added aliases to avoid having weird collisions).

The main two changes of this PR are:
1. Dropping the double deployment (which didn't add but an exporter in the daemonset) 
2. Dropping the config defaults, and adding all options as aliases with no pre-existing checks

1) should be easily overcome with the latest commit where I explain exactly what are the new parts that need to be added (the otlp exporter + registering the exporter in the pipelines)

2) Is a bit tricky. I think I would divide the users in two groups:

1. The people relying on the default config with all the flags enabled
2. The people having trouble overcoming the defaults to set the collector up with their own specific configuration

For the first group of people I believe the current README explains in much more depth (I'm actually not sure this is good thing but hey), the different extras (container logs, host monitoring, memory limits) with examples of complete configs. So I hope when upgrading they will see the warnings and the different examples

For the second group of people, I believe dropping the current config is going to be welcomed and shouldn't pose a problem, taking into account that they are probably very aware on how a good collector config should look like (I assume if you are able to create the file filters for your own file log monitoring, you are probably good understand the explanations). On top of that, for them it will now be easier to look at how the config's template is done if trying to go for more advanced configurations than the ones provided, and that the change of dropping all defaults instead of having to overcome the previous multi-step override will result in a easier migration.

I took the idea of dropping all defaults from the collector, so hopefully users have already contemplated using the operator and are happy to provide complete collector configurations.

How do you see it?

**Comment by TylerHelmuth** [comment]
In addition to a detailed README section on how existing "both" users can transition to the double install I think we should supply some example values.yamls/renders. Could pair well with #141.

**Comment by dmitryax** [comment]
@TylerHelmuth sounds good. Do you think we should have #141 before this handling this issue?

**Comment by TylerHelmuth** [comment]
We certainly could, but I was hoping to do #138 before doing #141 but #138 is blocked by this issue. We could complete both issues with less interesting example and then add/adjust the examples once this refactor is done. But the examples in #138 will essentially be exactly like our CI folder until we can improve our override capabilities with this PR.

**Comment by dmitryax** [comment]
I think currently we can have at least these for use cases:
- agent only configuration
- standalone only configuration
- agent and standalone

They will stay after the refactoring, the third one will be applied as two chart installations which is pretty important use case to illustrate for the transition.

**Comment by TylerHelmuth** [comment]
Sounds good

**Comment by TylerHelmuth** [comment]
@dmitryax ready to close this issue?

**Comment by dmitryax** [comment]
Yes, I believe so. Thanks for all the work @TylerHelmuth!
